apiVersion: app/v1
kind: Deployment
metadata:
  app: speeddepolyment
  
spec:
  replicas: 3
  selector:
    matchLables:
      app: speed
      version: "1.0"

template:
  metadata:
   labels:
      app: speed
      version: "1.0"
  spec:  
   containers:
    - name: speed
      image: mahesh/speed:1.0
        ports: 
         - name: speedport
           containerport: 8080
           protocal: TCP  
